### ISSUE TITLE
Doesn't work at all in TOR Browser

### ISSUE THREAD

**Issue by jhtitor** [cla-assistant/cla-assistant#471] opened 2019-08-07 13:49 UTC
Not sure if that's a TOR Browser issue, or a generic Firefox issue, but that's what I see when I visit https://cla-assistant.io/

![cla-nothing](https://user-images.githubusercontent.com/34790146/62627907-d0358480-b919-11e9-8c74-468f8039cf84.png)

If that's of any help, here's the console output:

![cla-console](https://user-images.githubusercontent.com/34790146/62627922-d62b6580-b919-11e9-9956-77835674366e.png)

That happens all the time, i.e. 100% reproducible.

I'm using TOR Browser 8.5.4 (based on Mozilla Firefox 60.8.0esr) (64-bit), on Linux.

**Comment by ibakshay** [comment] 2019-08-07 17:12
Hi @jhtitor, We were facing technical issue lately and it was not browser-specific.  Now https://cla-assistant.io/ is working fine and I checked in Google Chrome Browser. Can you check in your TOR Browser now and let us know If you are still facing the issue so that we will know whether It is a generic issue or specific to TOR browser.

**Comment by jhtitor** [comment] 2019-08-07 18:07
@ibakshay, thanks for the quick reply, I've checked again, and it's the same - an empty page, and a bunch of templating/angular.js errors in the console.

**Comment by ibakshay** [comment] 2019-08-08 14:25
@jhtitor oh that's bad:/. And you have tried in another browser also right ?. 
Just to make sure whether the issue is Tor Browser specific or the issue is with your Github account linking CLA Assistant.

**Closed** 2019-11-13 19:39 UTC
Labels: wontfix
