### ISSUE TITLE
Unable to sign CLA due to SSL error 

### ISSUE THREAD

**Issue by dabd** [cla-assistant/cla-assistant#609] opened 2020-08-12 10:34 UTC
URL to the linked Repo/Org:

Steps to reproduce the problem:

1. Attempt to sign CLA in https://cla-assistant.io/disneystreaming/weaver-test?pullRequest=50
2.
3.

What is the expected result?

What happens instead?

The following SSL errors are shown:
(see screenshot below)

(

**Comment by dabd** [comment] 2020-08-12 10:35
<img width="1435" alt="Screenshot 2020-08-12 at 11 27 46" src="https://user-images.githubusercontent.com/167463/90005947-ecd46d00-dc8f-11ea-91f5-47167224bb92.png">

**Comment by KharitonOff** [comment] 2020-08-13 10:13
Unfortunately I can not reproduce the issue :( 
@ibakshay , @michael-spengler do you have the same issue with this PR?

**Comment by ibakshay** [comment] 2020-08-15 07:09
@KharitonOff, I am also not able to reproduce the issue :/.
@dabd, it looks like you have merged this PR https://github.com/disneystreaming/weaver-test/pull/50. Could you tell us on how you have resolved this issue?

**Comment by dabd** [comment] 2020-08-15 10:13
> @KharitonOff, I am also not able to reproduce the issue :/.
> @dabd, it looks like you have merged this PR [disneystreaming/weaver-test#50](https://github.com/disneystreaming/weaver-test/pull/50). Could you tell us on how you have resolved this issue?

@ibakshay I simply tried again on the next day :)

**Comment by ibakshay** [comment] 2020-08-15 10:17
@dabd Hehe, okay 😉 . I will close this issue then, Feel free to reach out to us again If you require any assistance from our side :).

**Closed by ibakshay** 2020-08-15 10:17 UTC
Labels: help wanted
