### ISSUE TITLE
 signed CLA but assistant still says not signed.

### ISSUE THREAD

**Issue by fbalicchia** [cla-assistant/cla-assistant#265] opened 2017-10-15 18:36 UTC
Hi,
I've signed CLA but assistant still says not signed. 
[Cla signed](https://www.dropbox.com/s/98mr4tmlnqtfwaq/Clasigned.png?dl=0
)
My userid is fbalicchia@gmail.com and it the only git account present.
I've checked email settings section in my account and it is configure corretly.
Pull request that Assistant need to approve is 
https://github.com/Graylog2/graylog2-server/pull/4247.
Have you any suggest to resolve this problem ?
Thanks for help

--Filippo

**Comment by joschi** [comment] 2017-10-15 20:51
@fbalicchia As far as I see the problem is that the email address which committed the changes (`filippo<DOT>balicchia<AT>openmindonline<DOT>it`) isn't registered in your GitHub account as a secondary email address.

Also see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by KharitonOff** [comment] 2017-10-16 08:02
Thanks @joschi

**Closed by KharitonOff** 2017-10-16 08:02 UTC
