### ISSUE TITLE
Whitelisting organization doesn't seem to work

### ISSUE THREAD

**Issue by diwakergupta** [cla-assistant/cla-assistant#521] opened 2020-01-06 15:30 UTC
URL to the linked Repo/Org:
https://github.com/blockstack/docs.blockstack/pull/487
https://cla-assistant.io/blockstack/docs.blockstack?pullRequest=487

Steps to reproduce the problem:

1. Link CLA assistant to an organization, in this case https://github.com/blockstack
2. Whitelist `blockstack`, see screenshot. Perhaps I'm not using the correct format?
3. PR submitted by a member of the organization (specifically `moxiegirl`) triggers the CLA check.

<img width="780" alt="Screenshot 2020-01-06 10 27 58" src="https://user-images.githubusercontent.com/15990/71827962-5e4f9b80-306f-11ea-9e3c-e5ae75b565af.png">

What is the expected result?
CLA check should not have been needed, since organization is whitelisted.

What happens instead?
CLA check is triggered.

**Comment by moxiegirl** [comment] 2020-01-10 02:46
@diwakergupta this is a recent development...it used to work.

**Comment by ibakshay** [comment] 2020-01-10 13:23
hI @diwakergupta, I just tested whitelisting organisation functionality and it works fine. I just reviewed this [Pull Request](https://github.com/blockstack/docs.blockstack/pull/487) and it looks fine now. Maybe, some other issue has affected this PR. I can also  see there is a duplicate comment in your PR, which is a bug from our side and we are working on it.
Feel free to reach out to us again.

**Comment by nycnewman** [comment] 2020-01-14 16:53
We have seen an issue where if Github thinks there are two authors for a PR - one internal and one external - cla assistant appears to require the internal (org member) to sign a CLA incorrectly. Haven't had time to dig into code.

**Comment by ibakshay** [comment] 2020-01-16 13:30
> We have seen an issue where if Github thinks there are two authors for a PR - one internal and one external - cla assistant appears to require the internal (org member) to sign a CLA incorrectly. Haven't had time to dig into code.

@nycnewman We aren't able to reproduce this scenario. It will be great If you can provide us with the affected Pull Request for analysing this issue.

**Comment by diwakergupta** [comment] 2020-01-16 15:49
@ibakshay any update on the duplicate comment bug? Still happening (E.g. https://github.com/blockstack/blockstack-core/pull/1228). Is there an issue tracking it, so I can follow it along for fixes?

**Comment by ibakshay** [comment] 2020-01-20 16:29
@diwakergupta , I am sorry for this bug. We are yet to find the root cause and we are working on it. There is no issue tracking as such, However, I will let you soon after we have deployed the fix 😄 .

**Comment by ibakshay** [comment] 2020-01-21 12:05
@diwakergupta, Can you please check and tell us,  if there is a  CLAAssistant webhook in the repository `blockstack-core`? 
It will help us with debugging this issue.

**Comment by diwakergupta** [comment] 2020-01-21 17:48
@ibakshay yes, there is:

<img width="736" alt="Screenshot 2020-01-21 12 46 44" src="https://user-images.githubusercontent.com/15990/72829130-28eca580-3c4c-11ea-8a33-c2843ffe845e.png">

Here are some recent deliveries if it helps:

<img width="757" alt="Screenshot 2020-01-21 12 48 26" src="https://user-images.githubusercontent.com/15990/72829205-56395380-3c4c-11ea-8e6e-c86a35e5ea5a.png">

**Comment by KharitonOff** [comment] 2020-01-22 13:38
If you have linked the whole organization, then there shouldn't be any webhook on repository level. 

Probably CLA assistant didn't mange to delete its webhook from this repository and now it receives two webhook requests (one from the org and one from the repo). We will fix this on our side as soon as possible.

As a quick fix for you we suggest to delete the web-hook on repository level manually.

**Comment by BIGPHATTOBY** [comment] 2020-02-13 14:41
Any news on this issue? adding our org to the list of whitelist yields nothing while adding individual names makes it possible to skip the CLA.

> If you have linked the whole organization, then there shouldn't be any webhook on repository level.
> 
> Probably CLA assistant didn't mange to delete its webhook from this repository and now it receives two webhook requests (one from the org and one from the repo). We will fix this on our side as soon as possible.
> 
> As a quick fix for you we suggest to delete the web-hook on repository level manually.

So for org whitelist to work, the webhook must come from the org only?

**Comment by KharitonOff** [comment] 2020-02-13 15:41
> So for org whitelist to work, the webhook must come from the org only?

For org whitelist to work, the **Pull Request** must come from the org (e.g. Pull Request from dev branch to master of the same repository or Pull Request from a fork of the whitelisted organization). Unfortunately it won't work if the member of the org opens a PR from his own fork.

**Comment by KharitonOff** [comment] 2020-02-19 12:24
As whitelisting feature is working as designed, we are closing this issue. Feel free to reopen in case of any further questions or problems with regards to this.

**Closed by KharitonOff** 2020-02-19 12:24 UTC
