### ISSUE TITLE
Getting "Contributor License Agreement is not signed yet." when pushing a pull request

### ISSUE THREAD

**Issue by lauraanddolay** [cla-assistant/cla-assistant#858] opened 2022-03-30 08:57 UTC
Getting Contributor License Agreement is not signed yet. although it already has been.

## URL to the linked Repository or Organization

https://github.com/kyma-incubator/reconciler/pull/978
## Steps to reproduce the problem

1. create a PR it asked for 
<img width="919" alt="image" src="https://user-images.githubusercontent.com/98089303/160792202-972e9199-dd3e-474d-8f16-a2aeb7b1d8ba.png">
2. then i click the above `[Contributor License Agreement](https://cla-assistant.io/kyma-incubator/reconciler?pullRequest=978)`, it shows the  License contents , however the CLA is still pending status...
```
 ---Copyright License. ****
 --- Patent License.
```

## What is the expected result?
`Contributor License Agreement is signed.`
## What happens instead?
contributor License Agreement is not signed yet.

## Any other tested browsers/devices(OK/FAIL):
If i click https://cla-assistant.io/, and sign-in with Github and then `View my singed CLAs` which seems signed in
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/98089303/160793091-7bb6f9f4-f3ac-49ea-a563-bae55b8771f1.png">

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/98089303/160791842-8087a414-28b7-4612-a7cb-94987b186068.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/98089303/160791935-77bb4ba4-6257-46c8-8c22-2e6763897079.png">

**Comment by Shegox** [comment] 2022-03-30 09:10
Hi @lauraanddolay, 

the problem is that both the person opening the PR as well as each commiter needs to sign the CLA.
In your case you opened the PR, while the commit ([`e955808`](https://github.com/kyma-incubator/reconciler/commit/e955808c51f6cf0d42c35cb7b8cf0392cc9441da.patch)) is associated with @lauraanddola.

You will need to either: 
- Sign in as @lauraanddola to CLA-assistant and sign the CLA as well
or
- Recreate the commits with an email associated to your @lauraanddolay account
or 
- remove the `laura.dong@sap.com` email from @lauraanddola and add it to @lauraanddolay and trigger a recheck.

**Comment by lauraanddolay** [comment] 2022-03-30 09:18
hi @Shegox, I try to login the @lauraanddola account but it always asked me to input `Two-factor authentication` but i don't contain that digit numbmer and recovery code, what should i do ?

**Comment by Shegox** [comment] 2022-03-30 09:23
@lauraanddolay you can try reaching out to GitHub support for [Recovering your account if you lose your 2FA credentials
](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials). 

If that doesn't work, or you don't want to wait for that. You need to "recreate" your commits with an email which is associated with your current account. 
This can normally done using (replace with your actual email): 
```bash
# Recreate last commit using a different Git author 
git commit --amend --author="John Doe <john@doe.org>"
# Force update the branch to overwrite the old commit
git push --force
```

**Comment by lauraanddolay** [comment] 2022-03-30 09:33
hi @Shegox , I try to execute below cmds and then reassigned CLA but it seems still `pending` in https://github.com/kyma-incubator/reconciler/pull/978 ....
```
$ git commit --amend --author="laura.dong@sap.com"
[add_plan_name df73d3b] test cla
 Date: Wed Mar 30 16:32:10 2022 +0800
 1 file changed, 2 insertions(+), 2 deletions(-)
$ git push --force
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 492 bytes | 123.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/kyma-incubator/reconciler.git
 + e955808...df73d3b add_plan_name -> add_plan_name (forced update)
```

**Comment by Shegox** [comment] 2022-03-30 09:34
`laura.dong@sap.com` is associated with @lauraanddola. You need to use one of the emails listed in https://github.com/settings/emails

**Comment by lauraanddolay** [comment] 2022-03-30 09:40
hi @Shegox https://github.com/settings/emails contains `lauraanddola@sina.com` and it reported error , what should i do ? thanks.
```
git commit --amend --author="lauraanddola@sina.com"
fatal: --author 'lauraanddola@sina.com' is not 'Name <email>' and matches no existing author
````

**Comment by Shegox** [comment] 2022-03-30 09:41
This command should work, you need to provide both a name and in `<email>` an email: 
```bash 
git commit --amend --author="Laura Dong <lauraanddola@sina.com>"
```

**Comment by lauraanddolay** [comment] 2022-03-30 09:44
hi @Shegox finally it works and many thanks.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/98089303/160802489-48e9fb0a-5807-4be6-a41b-c2e321127701.png">

**Comment by Shegox** [comment] 2022-03-30 09:46
Great 👍 

You should anyway go ahead and open a ticket with GitHub to either recover your old account. Or, if that doesn't work, get your SAP email removed from that account, so you can add it your current account to avoid this problem in the future. 

I'm going ahead and close this issue for now.

**Closed by Shegox** 2022-03-30 09:46 UTC
