### ISSUE TITLE
Unable to configure CLA until I disable Organisation Third-party application access policy

### ISSUE THREAD

**Issue by paddyfeerick** [cla-assistant/cla-assistant#506] opened 2019-11-08 14:03 UTC
URL to the linked Repo/Org: N/A

## Steps to reproduce the problem:

1. Create a new organisation and repo
2. Sign-in to cla-assistant as the organisation owner  
3. Configure the CLA for this repo

## What is the expected result?
 The repo is configurable
## What happens instead?
 Neither the organisation or repo is listed. However if I disable the 3-party application access setting for the organisation and refresh it I am then able to see the repos. This seems odd to me, and from my recall of a prior repo config  (several weeks ago) I didn't seem to need to do this. I stand corrected!

**Comment by ibakshay** [comment] 2019-11-12 12:24
Hi @paddyfeerick, Thank you for reaching out to us. This is an expected behaviour and by design and So, Unfortunately, We can't really do anything about it. 

One thing you can do is to by going to your profile `settings -> applications -> Authorized OAuth Apps` and then select request access grant to all the new organisations which you need to link with CLA Assistant. 

<img width="771" alt="Screenshot 2019-11-12 at 13 15 06" src="https://user-images.githubusercontent.com/33329946/68671432-96df6700-054f-11ea-8fd2-b1023993625a.png">

**Comment by paddyfeerick** [comment] 2019-11-12 15:57
Many thanks!  The steps you've described above work for me - I trialled it on a  new org and no longer have to 'open up'  the 3-party org application access setting.

**Comment by ibakshay** [comment] 2019-11-13 09:26
sounds great .. I will close this issue then and Nevertheless, Feel free to reach to us again  anytime if you need any further assistance.

**Closed by ibakshay** 2019-11-13 09:26 UTC
