### ISSUE TITLE
"Recheck PRs" button did not seem to work

### ISSUE THREAD

**Issue by jcarsique** [cla-assistant/cla-assistant#510] opened 2019-11-12 17:49 UTC
Hello,

URL to the linked Repo/Org: the whole https://github.com/nuxeo/ organization.
PR https://github.com/nuxeo/nuxeo-jsf-ui/pull/21 was stuck on waiting for status.

## Steps to reproduce the problem:

1. Create a PR 
2. Sometimes, the status is not updated: `license/cla Expected — Waiting for status to be reported`
3. I clicked on the "Recheck PRs" button at https://cla-assistant.io/ but no change
4. Accordingly to #433 I checked that the organization link is still active. It looks fine.
5. Accordingly to #476 I tried https://cla-assistant.io/check/nuxeo/nuxeo-jsf-ui?pullrequest=21 but no change ; 

What is the average duration of the "Recheck PRs" button? Is it reasonable to think that it failed if nothing changed after 30min?

Is this API call expected to work when CLA is linked to the org, not the repo?

##  What is the expected result?

Status refresh at https://github.com/nuxeo/nuxeo-jsf-ui/pull/21

## What happens instead?

Nothing 

## Optional

Workaround: pushing an empty commit seem to have finally triggered the recheck.
`git commit -m"trigger CLA check" --allow-empty`

Possible cause: in the current case, there's been a force push. I can't tell if the issue happened before the force push, nor if it only happened on PRs with force pushed commits.

**Comment by KharitonOff** [comment] 2019-11-13 08:37
Thank you very much for well described issue!
@ibakshay let's check whether we can reproduce the issue with force pushed commits.

**Comment by KharitonOff** [comment] 2020-05-18 07:56
I believe, this issue represents the same problem like #520.
Let's close this one, since a workaround helped here and keep tracking the #520

**Closed by KharitonOff** 2020-05-18 07:56 UTC
Labels: wontfix
