### ISSUE TITLE
license/cla check fails to report for recent PRs

### ISSUE THREAD

**Issue by meiliang86** [cla-assistant/cla-assistant#774] opened 2021-09-21 05:57 UTC
licence/cla check is not reporting back for all our recent PRs https://github.com/uber/cadence/pulls

**Comment by Shegox** [comment] 2021-09-21 06:24
I'm looking into it. From a first look at the logs it looks like it correctly receives and tries to update the PR status but then stop for whatever reason: 
```js
jsonPayload: {
  hostname: "localhost"   
  level: 20   
  msg: "StatusService-->createStatus for the repo uber/cadence/pull/4498"   
  name: "cla-assistant.io"   
  pid: 13   
  src: {
   file: "/cla-assistant/src/server/services/status.js"    
   func: "createStatus"    
   line: 64    
  }
  v: 0   
 }
```

**Comment by Shegox** [comment] 2021-09-21 06:35
Found the problem. 

CLA-assistant uses the token of the user who configured it to perform actions. In this case the user, who did the setup for the whole _uber_ organization is now longer part of the the _uber_ organization and therefore the token is now longer allowed to update the commit Status. 

To resolve this, please get one of your open source/GitHub admins to go to https://cla-assistant.io and and link the organization again as described in https://github.com/cla-assistant/cla-assistant/blob/master/COMMON_ISSUES.md#unable-to-link-organization. 

This will update the used tokens and should fix the problems. The admin can then as well hit the "Recheck PRs" in the organization settings in CLA-assistent to trigger a recheck. 
Alternatively you can manually recheck them with curl-ing or just browsing to `https://cla-assistant.io/check/uber/cadence?pullRequest=4500`.

**Comment by meiliang86** [comment] 2021-09-21 06:38
Thanks a lot @Shegox !

**Comment by longquanzheng** [comment] 2021-09-21 06:48
@Shegox can you help me with this one? I have been trying very hard to merge it https://github.com/uber/cadence/pull/4498

Thanks in advance!

**Comment by Shegox** [comment] 2021-09-21 06:58
@longquanzheng the prerequisite to get it working again is that someone from the uber organization admins goes to cla-assistant.io and updates the authentication. Only afterwards either the "curl" or the "recheck PRs" will work again. Currently the problem is that cla-assistant has no valid token with enough permissions to update the commit status and therefore "nothing" happens. 

You can find the owners of the uber organization here: https://github.com/orgs/uber/people?query=role%3Aowner

**Comment by Shegox** [comment] 2021-09-23 07:48
@meiliang86 @longquanzheng I see that it is now working again (e.g. https://github.com/uber/cadence/pull/4501). Therefore I'm going ahead and close the issue. If there are still problems, please open a new issue. Many thanks.

**Closed by Shegox** 2021-09-23 07:48 UTC
