### ISSUE TITLE
https://cla-assistant.io/ unstable

### ISSUE THREAD

**Issue by derberg** [cla-assistant/cla-assistant#451] opened 2019-07-01 10:50 UTC
Since few days, from time to time it is taking a lot of time to log into https://cla-assistant.io/ and also CLA checks are slow in response, I clicked "recheck" more times in few last few days that I had to in last few years.
Sometime error is Error 524

Are you aware of the problem?

**Comment by KharitonOff** [comment] 2019-07-01 11:23
Thanks for the issue. We've noticed some outages and log response times from time to time too. Unfortunately we weren’t able to find the root cause yet. It would be very helpful if you could provide us a more specific timeframe next time you notice an outage/long delay in response, please.

**Comment by derberg** [comment] 2019-07-01 11:50
the current issue started few minutes before I created this issue and it is still ongoing, CLA can't be used at all.
I just tried to access it from public internet

![Screen Shot 2019-07-01 at 13 49 05](https://user-images.githubusercontent.com/6995927/60434301-202c7780-9c07-11e9-8ab2-776ce4bf31d3.png)

**Comment by KharitonOff** [comment] 2019-07-01 15:43
It should work well again. The problem is not solved completely. Let's keep this issue open.

**Comment by derberg** [comment] 2019-07-02 11:55
The issue is still there. POST to recheck PRs also fails with 524

![Screen Shot 2019-07-02 at 13 53 31](https://user-images.githubusercontent.com/6995927/60510903-e9229880-9cd0-11e9-9465-6d7d1f147693.png)

**Comment by ibakshay** [comment] 2019-07-02 12:02
It should work now. We are looking into this issue for a permanent solution.

**Comment by derberg** [comment] 2019-07-04 14:50
sorry guys but looks like this is happening again. Once the UI loads after all those errors, I can trigger "Recheck" and see the POST call after long run ends with 200 but nothing happens, the Pr is still hanging https://github.com/kyma-project/kyma/pull/4752

![Screen Shot 2019-07-04 at 16 48 41](https://user-images.githubusercontent.com/6995927/60675010-b7016a00-9e7b-11e9-923b-078c51b5a9e0.png)

**Comment by KharitonOff** [comment] 2019-07-04 15:34
Hi Lukasz, no problem. Feel free to report the issue any time. I just retriggered the check for this specific PR, it looks good now. In case you'll need it, you can use the API GET call: https://cla-assistant.io/check/kyma-project/kyma?pullRequest=4752 
We are still searching for the root cause of the performance problems.

**Comment by rsora** [comment] 2019-07-09 06:43
Hi there,
Unfortunately, I have a similar problem: 
My PR is stuck in pending state on the CLA check since yesterday, when it was created  (https://github.com/arduino/arduino-cli/pull/267)

I asked for check multiple times via https://cla-assistant.io/check/arduino/arduino-cli?pullRequest=267 but nothing happens.
![image](https://user-images.githubusercontent.com/35916119/60864637-6fd0fb80-a224-11e9-95cd-1f8714c47739.png)

In addition I experience a not consistent behaviour here 
https://cla-assistant.io/arduino/arduino-cli?pullRequest=267
sometimes I'm asked for signing, sometimes I get I have correctly signed the CLA.

Please consider also that I have already signed the CLA a month ago more or less, from my office network, and now I'm working from home.

Please let me know if I can provide something more to help the troubleshooting. Thanks!

**Comment by ibakshay** [comment] 2019-07-09 07:26
Hi @rsora, I have checked your issue and it looks like the `ArduinoBot` has committed in this pull request  (https://github.com/arduino/arduino-cli/pull/267). Could you please check If you have whitelisted 'ArduinoBot' otherwise the CLA Assistant will consider this bot as a  `user` and It expects a signature from `ArduinoBot` 

<img width="831" alt="Screen Shot 2019-07-09 at 09 11 30" src="https://user-images.githubusercontent.com/33329946/60867513-55e6e700-a22b-11e9-8f04-8ec9cff5a8cf.png">

**Comment by rsora** [comment] 2019-07-09 08:07
@ibakshay OMG thanks, I didn't noticed it at all :blush: 
Sorry for creating noise in the issue!

**Comment by ibakshay** [comment] 2019-07-09 23:41
hi @derberg, We have done the potential fix for the performance issue which you have experienced recently. Could you tell us if you are still facing the performance related issue?

**Closed** 2020-01-13 10:48 UTC
Labels: wontfix
